name: Biome
description: Run Biome Format & Lint Check

on:
  workflow_call:
    inputs:
      bun-version-file:
        required: false
        type: string
        default: "mise.toml"
      biome-version:
        required: false
        type: string
        default: "latest"
      check-path:
        required: false
        type: string
        default: "."

jobs:
  format:
    name: Biome
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Source
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        with:
          bun-version-file: ${{ inputs.bun-version-file }}

      - name: Biome Check
        run: bunx --bun @biomejs/biome@${{ inputs.biome-version }} ci ${{ inputs.check-path }}
