name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  biome-format-lint-check:
    name: Check
    uses: SnakeDoc/wontonium/.github/workflows/biome.yaml@76831dc7d802246431a042c979a584a222702b12 # main
