name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  biome-format-lint-check:
    name: Check
    uses: SnakeDoc/wontonium/.github/workflows/biome.yaml@9fd12a52b76717fe47a5596ae8399cb8fffaec80 # main
